import React from 'react'
import Head from 'next/head'

import { AllCategories } from '../components/AllCategories'
import Navbar from '../components/Navbar'

const Category = () => {
    return (
        <div>
            <Head>
                <title>Baldgenie - Services at your doorsteps</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <AllCategories />
        </div>
    )
}

export default Category
