import React, { useState } from 'react'
import {
    SearchIcon, LocationMarkerIcon, CheckIcon, XIcon, DeviceMobileIcon, HomeIcon
} from '@heroicons/react/solid';
import Head from 'next/head'
import Services from '../components/Merchant/ServiceSignUp';
import { Gen_info_PART1 } from '../components/Merchant/Gen_info_PART1';
import { Gen_info_PART2 } from '../components/Merchant/Gen_info_PART2';


const MerchantSignUP = () => {



    return (
        <div className=' m-12 ml-28 font-footer'>
            {/* Primary Contact  */}

            <Head>
                <title>Baldgenie - Services at your doorsteps</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1 className=' mr-3 font-semibold text-xl m-6 ml-4'>{`{* symbol --> Mandatory}`}</h1>

            <Gen_info_PART1 />
            {/* <Gen_info_PART2 /> */}


            <div className='mt-16'>
                {/* <Services /> */}
            </div>
        </div>
    )
}
export default MerchantSignUP
