import React, { useState } from 'react'
import {
    SearchIcon, LocationMarkerIcon, CheckIcon, XIcon, DeviceMobileIcon, HomeIcon
} from '@heroicons/react/solid';
import Head from 'next/head'
import Services from '../components/Merchant/ServiceSignUp';
import { Gen_info_PART1 } from '../components/Merchant/Gen_info_PART1';
import { Gen_info_PART2 } from '../components/Merchant/Gen_info_PART2';


const MerchantSignUP = () => {



    return (
        <div className=' m-12 ml-28 font-footer'>
            {/* Primary Contact  */}

            <Head>
                <title>Baldgenie - Services at your doorsteps</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1 className=' mr-3 font-semibold text-xl m-6 ml-4'>{`{* symbol --> Mandatory}`}</h1>

            <form className="" action="#" method="POST">
                <Gen_info_PART1 />
                <Gen_info_PART2 />
                <button type="submit" className="group mx-auto relative text-lg  flex justify-center py-2 px-8 border border-transparent  font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 mt-14">Submit</button>
            </form>

            <div className='mt-16'>
                <Services />
            </div>
        </div>
    )
}
export default MerchantSignUP
